# Numpy
Numpy adalah package Python yang populer dan [dokumentasi](https://numpy.org/) lengkap. Digunakan untuk operasi  matematika

# Pandas
Pandas adalah package Python yang tidak kalah populer, dan digunakan untuk manipulasi data. Terutama data di 1 dan 2 dimensi. [Dokumentasi](https://pandas.pydata.org/) disini.

In [18]:
import numpy as np
import pandas as pd

biasanya numpy digunakan saat kita mau simpan data bersifat numerik.

dibandingkan List yang bisa menerima semua tipe data, numpy array di khususkan untuk tipe data numerik.

karena dia khusus numerik, dia memiliki banyak built-in function yang memudahkan proses aritmatik.

In [2]:
nilai = [25,79,36]
print(nilai, type(nilai))

[25, 79, 36] <class 'list'>


In [3]:
# nilai / 10

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [4]:
nilai_arr = np.array(nilai)
print(nilai_arr, type(nilai_arr))

[25 79 36] <class 'numpy.ndarray'>


In [5]:
nilai_arr / 10

array([2.5, 7.9, 3.6])

In [6]:
# pangkat
np.square(nilai_arr)

array([ 625, 6241, 1296], dtype=int32)

In [9]:
# CRUD
# Create numpy array
# 1. pakai np.array(diisi list)
print(np.array([1,2,3]))

# 2. pakai np.ones atau np.zeros untuk membuat angka2 yang sama 1 semua, 0 semua
print(np.ones(10))
print(np.zeros(3))

# 3. pakai np.random.random untuk membuat kumpulan angka random
print(np.random.random(5))

# 4. pakai np.arange untuk membuat angka urut, cara pakainya sama dengan cara pakai range
print(np.arange(10))
print(np.arange(10, 20))
print(np.arange(10, 100, 17))

[1 2 3]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0.]
[0.32990517 0.59649654 0.72025927 0.29404667 0.22023096]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 27 44 61 78 95]


In [12]:
# Data 2 dimensi
# 1. pakai np.array(diisi list)
print(np.array([[1,2,3], [4,5,6]]))

# 2. pakai np.ones atau np.zeros untuk membuat angka2 yang sama 1 semua, 0 semua
print(np.ones((5,2)))
print(np.zeros((3,4)))

# 3. pakai np.random.random untuk membuat kumpulan angka random
print(np.random.random((5,6)))

[[1 2 3]
 [4 5 6]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.45074327 0.27244338 0.36378494 0.94951777 0.16317003 0.91256904]
 [0.06065033 0.78061704 0.29966597 0.28534107 0.76972799 0.92962845]
 [0.85877761 0.99495566 0.35487278 0.39551133 0.79090745 0.73707745]
 [0.24515787 0.45516452 0.2201933  0.18655283 0.29238397 0.15130393]
 [0.83758081 0.77091456 0.65963143 0.97239605 0.47453258 0.8016922 ]]


In [13]:
# 4. pakai np.arange untuk membuat angka urut, cara pakainya sama dengan cara pakai range
print(np.arange(10).reshape((2, 5)))
print(np.arange(10, 20).reshape((5,2)))
print(np.arange(10, 100, 17).reshape((2,3)))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[[10 27 44]
 [61 78 95]]


In [15]:
# Read
# shape (bentuk numpy array)
nilai_arr.shape

(3,)

In [16]:
arr1 = np.ones((3,4))
print(arr1)
print(arr1.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)


In [17]:
# size, jumlah angka yang ada di dalam sebuah numpy array
print(nilai_arr.size)
print(arr1.size)

3
12


pandas - punya dua data struktur custom
- DataFrame (2 dimensi)
- Series (1 dimensi)

In [20]:
df_mi = pd.read_excel("Median Income US.xlsx")
df_mi

job  median annual wage
0          admin.             40990.0
1      technician             54760.0
2        services             26090.0
3      management            109760.0
4         retired             75254.0
5     blue-collar             33230.0
6      unemployed                 0.0
7    entrepreneur             70849.0
8       housemaid             30225.0
9         unknown                 NaN
10  self-employed             85962.0
11        student             36304.0

In [21]:
df_mi.to_excel("MedianIncomeUS2.xlsx")

# Assignment sesi 16
## Exploring Data Analysis with Python and NumPy

1. buat python notebook assignment_sesi16.ipynb
    - berikan introduction dalam markdown ini file apa
    - import package yang akan digunakan di atas
2. download data, misalnya dari [diabetes.csv](https://raw.githubusercontent.com/stefkwan-h8/dataset/main/diabetes.csv)
3. load data ke dalam file notebook yang sudah dibuat

### Data Exploration
4. hitung untuk pilihan kolom:
    - mean (rata-rata) - np.mean()
    - median - np.median()
    - standard deviation - np.std()
    - minimum - np.min()
    - maximum - np.max()
* bisa gunakan Python, loop, if, manual, atau bisa pakai Numpy

### Data Manipulation
5. buat kolom baru di dataset menggunakan hasil aritmatik, misalkan kolom rasio BMI/Age atau lainnya
6. buat baris baru data, diisi angka2 random saja, atau angka2 mean juga boleh

### Data Filtering
7. filter dataset nya supaya kita cuma lihat baris2 data tertentu, misalnya, khusus yang Age dibawah 30
8. save data yang sudah di filter sebagai file csv baru

### Conclusion
9. apakah ada pattern data yang ditemukan? jika tidak, coba cari pattern data tertentu, dan jadikan konklusi hasil data analysis

### Submission
10. submit file notebook ke Google Classroom


In [22]:
df_diabet = pd.read_csv("https://raw.githubusercontent.com/stefkwan-h8/dataset/main/diabetes.csv")
df_diabet

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [25]:
umur = df_diabet["Age"]
umur

0      50
1      31
2      32
3      21
4      33
       ..
763    63
764    27
765    30
766    47
767    23
Name: Age, Length: 768, dtype: int64

In [27]:
arr_umur = np.array(umur)
print(arr_umur.mean())
print(np.median(arr_umur))
print(arr_umur.std())
print(arr_umur.min())
print(arr_umur.max())

33.240885416666664
29.0
11.752572645994181
21
81
